### ISSUE TITLE
Required Markup

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred-fa-editor#1]
Hi, more and more I'm getting into Fred. But now I am stuck again.
I'm not sure if it is a bug or my fault.

Which Markup is required to use the icon editor in Fred?
`<i class="fab fa-html5 fa-4x" data-fred-name="icon"></i>`

I'm only getting this:
![grafik](https://user-images.githubusercontent.com/41062056/44272874-4723ca00-a23e-11e8-899b-711ba3e7bcac.png)

Thank you in advance!

**Comment by theboxer** [comment]
This is the default Icon Editor that ships with Fred. If you want to use the FA Editor (this repo), you need to change a system setting `fred.icon_editor` to `FAEditor`.

All new installs of the FA Editor will do this step automatically.
