### ISSUE TITLE
Fred FA Editor 1.0.0-beta3 Publishing on Modx extras repository

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred-fa-editor#3]
Hi,

Will this package be added to the Modx extras store for automatic update?
I tried to upload manually the package to my current dev area that had the 1.0.0-beta2 from the Modx extras store and it didn't allow to upgrade. It installed like a new different extra:
![image](https://user-images.githubusercontent.com/22750391/60129390-c81bee00-978c-11e9-9b68-f23b4cb934ba.png)

The same is happening with Fred TinyMCE RTE:
![image](https://user-images.githubusercontent.com/22750391/60129487-01545e00-978d-11e9-8192-d5cfac39f348.png)

This is not happening with Fred (as an example).

**Comment by theboxer** [comment]
The latest version will be released with fred 1.1.0
